version: '3.3'
services:
  shiny-cromwell-preview:
    networks:
      - proxy
    environment:
      - PROOF_API_BASE_URL=https://proof-api-dev.fredhutch.org
    image: sc-registry.fredhutch.org/shiny-cromwell-preview:latest
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.shiny-cromwell-preview.rule=Host(`proof-dev.fredhutch.org`)"
        - "traefik.http.routers.shiny-cromwell-preview-secured.rule=Host(`proof-dev.fredhutch.org`)"
        - "traefik.http.routers.shiny-cromwell-preview.entrypoints=web,web-secured"
        - "traefik.http.services.shiny-cromwell-preview.loadbalancer.server.port=3838" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.shiny-cromwell-preview.tls=true"


networks:
  proxy:
    external: true
